language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ryusoumtkh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ryusoumtkh/react-test yarn test -- --coverage

after_success:
  - docker build -t ryusoumtkh/multi-client ./client
  - docker build -t ryusoumtkh/multi-nginx ./nginx
  - docker build -t ryusoumtkh/multi-server ./server
  - docker build -t ryusoumtkh/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ryusoumtkh/multi-client
  - docker push ryusoumtkh/multi-nginx
  - docker push ryusoumtkh/multi-server
  - docker push ryusoumtkh/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-1-783222145546
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
