version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker-compose build
      - run: echo "$DOCKER_PASSWORD" | docker login -u ${DOCKER_ID} --password-stdin
      - run: docker push
